# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_parent',
            new_name='parent',
        ),
    ]
