# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0002_auto_20170427_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textquestion',
            name='answer',
        ),
    ]
