# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0006_auto_20170427_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.CharField(max_length=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='Tree.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='node',
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_questions', to='Tree.Homework'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_questions', to='Tree.Homework'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
