# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0007_auto_20170427_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='quiz',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='textquestion',
            old_name='quiz',
            new_name='homework',
        ),
    ]
