# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0008_auto_20170427_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
