# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0009_node_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
