# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0011_auto_20170501_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='correct_answer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homework',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
