# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0012_auto_20170501_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='choice_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='choice_question',
            field=models.BooleanField(default=False),
        ),
    ]
